package poc.raviraj.gwtapp.shared;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue("department")
public class Department extends MasterType{

	private static final long serialVersionUID = 1L;
	
	public Department(){
		//required for generating proxy.. proxy is generated by the gwt compiler
	}

}
