package poc.raviraj.gwtapp.shared;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue("gender")
public class Gender extends MasterType {

	private static final long serialVersionUID = 1L;

	public Gender(){
		//required for generating proxy.. proxy is generated by the gwt compiler
	}
}
