package poc.raviraj.gwtapp.shared;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@Entity
@DiscriminatorValue("role")
public class Role extends MasterType{

	private static final long serialVersionUID = 1L;
	
	public Role(){
		//required for generating proxy.. proxy is generated by the gwt compiler
	}
}

